@startuml
title Архитектура разрабатываемой информационно-аналитической системы

top to bottom direction
skinparam componentStyle rectangle
skinparam shadowing true
skinparam packageStyle rectangle
skinparam linetype ortho

actor "Пользователь" as User

rectangle "Пользовательский интерфейс" as Frontend

package "Серверная часть" as Backend {
  [Модуль авторизации] as Auth
  [Модуль импорта и предпросмотра] as Import
  [Модуль предобработки] as Prep
  [Модуль сравнительного анализа] as Analysis
  [Модуль проектов и истории] as Storage
  [Модуль отчетности] as Reports
  
}

database "Реляционная база данных" as DB
cloud "Объектное хранилище данных" as S3

User --> Frontend
Frontend --> Backend

Auth --> DB
Import --> DB
Import --> S3
Prep --> DB
Analysis --> DB
Storage --> DB
Storage --> S3
Reports --> DB
Reports --> S3

Import --> Prep
Prep --> Analysis
Analysis --> Storage
Analysis --> Reports

@enduml